// 作品数据集中放在这里，后续替换图片、GIF、视频、标题和品牌最方便。
// 图片建议放到 public/works，视频建议按分类和品牌放到 public/media。
export const works = [
  {
    id: 1,
    title: "HYPER Energy Lab",
    type: "品牌视觉",
    category: "branding",
    brand: "HYPER",
    cover: "/works/work-hyper.svg",
    images: ["/works/work-hyper.svg", "/works/brand-detail-01.svg"],
    mediaType: "image",
    featured: false
  },
  {
    id: 2,
    title: "AURORA Technology",
    type: "品牌视觉",
    category: "branding",
    brand: "AURORA",
    cover: "/works/work-aurora.svg",
    images: ["/works/work-aurora.svg"],
    mediaType: "image",
    featured: false
  },
  {
    id: 3,
    title: "VOID BLOOM Fragrance",
    type: "品牌视觉",
    category: "branding",
    brand: "VOID BLOOM",
    cover: "/works/work-void.svg",
    images: ["/works/work-void.svg"],
    mediaType: "image",
    featured: false
  },
  {
    id: 4,
    title: "MUTANT Collection Store",
    type: "品牌视觉",
    category: "branding",
    brand: "MUTANT",
    cover: "/works/work-mutant.svg",
    images: ["/works/work-mutant.svg"],
    mediaType: "image",
    featured: false
  },
  {
    id: 5,
    title: "UNKNOWN Concept Brand",
    type: "品牌视觉",
    category: "branding",
    brand: "UNKNOWN",
    cover: "/works/work-unknown.svg",
    images: ["/works/work-unknown.svg"],
    mediaType: "image",
    featured: false
  },
  {
    id: 101,
    title: "Grand Opening Announcement",
    type: "活动视觉",
    category: "event",
    brand: "Babyback",
    cover: "/media/EVENT/Babyback/Babyback-Grand Opening Announcement.mp4",
    poster: "/media/EVENT/Babyback/Babyback-Grand Opening Announcement-poster.jpg",
    images: ["/media/EVENT/Babyback/Babyback-Grand Opening Announcement.mp4"],
    mediaType: "video",
    featured: true
  },
  {
    id: 102,
    title: "Live Action Compositing",
    type: "活动视觉",
    category: "event",
    brand: "Babyback",
    cover: "/media/EVENT/Babyback/Babyback-Live Action Compositing.mp4",
    poster: "/media/EVENT/Babyback/Babyback-Live Action Compositing-poster.jpg",
    images: ["/media/EVENT/Babyback/Babyback-Live Action Compositing.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 103,
    title: "1st Anniversary",
    type: "活动视觉",
    category: "event",
    brand: "Backup",
    cover: "/media/EVENT/Backup/Backup-1st Anniversary.mp4",
    poster: "/media/EVENT/Backup/Backup-1st Anniversary-poster.jpg",
    images: ["/media/EVENT/Backup/Backup-1st Anniversary.mp4"],
    mediaType: "video",
    featured: true
  },
  {
    id: 104,
    title: "2nd Anniversary Invitation",
    type: "活动视觉",
    category: "event",
    brand: "Backup",
    cover: "/media/EVENT/Backup/Backup-2nd Anniversary Invitation.mp4",
    poster: "/media/EVENT/Backup/Backup-2nd Anniversary Invitation-poster.jpg",
    images: ["/media/EVENT/Backup/Backup-2nd Anniversary Invitation.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 105,
    title: "520 Festival",
    type: "活动视觉",
    category: "event",
    brand: "Backup",
    cover: "/media/EVENT/Backup/Backup-520 Festival.mp4",
    poster: "/media/EVENT/Backup/Backup-520 Festival-poster.jpg",
    images: ["/media/EVENT/Backup/Backup-520 Festival.mp4"],
    mediaType: "video",
    featured: true
  },
  {
    id: 106,
    title: "Mid Autumn Festival",
    type: "活动视觉",
    category: "event",
    brand: "Backup",
    cover: "/media/EVENT/Backup/Backup-Mid Autumn Festival.mp4",
    poster: "/media/EVENT/Backup/Backup-Mid Autumn Festival-poster.jpg",
    images: ["/media/EVENT/Backup/Backup-Mid Autumn Festival.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 107,
    title: "Lantern Festival",
    type: "活动视觉",
    category: "event",
    brand: "Backup",
    cover: "/media/EVENT/Backup/Backup-Lantern Festival.mp4",
    poster: "/media/EVENT/Backup/Backup-Lantern Festival-poster.jpg",
    images: ["/media/EVENT/Backup/Backup-Lantern Festival.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 108,
    title: "Children Day",
    type: "活动视觉",
    category: "event",
    brand: "Backup",
    cover: "/media/EVENT/Backup/Backup-Children Day.mp4",
    poster: "/media/EVENT/Backup/Backup-Children Day-poster.jpg",
    images: ["/media/EVENT/Backup/Backup-Children Day.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 109,
    title: "Double 11 Promotion",
    type: "活动视觉",
    category: "event",
    brand: "Backup",
    cover: "/media/EVENT/Backup/Backup-Double 11 Promotion.mp4",
    poster: "/media/EVENT/Backup/Backup-Double 11 Promotion-poster.jpg",
    images: ["/media/EVENT/Backup/Backup-Double 11 Promotion.mp4"],
    mediaType: "video",
    featured: true
  },
  {
    id: 110,
    title: "Christmas",
    type: "活动视觉",
    category: "event",
    brand: "Backup",
    cover: "/media/EVENT/Backup/Backup-Christmas.mp4",
    poster: "/media/EVENT/Backup/Backup-Christmas-poster.jpg",
    images: ["/media/EVENT/Backup/Backup-Christmas.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 111,
    title: "April Fools Day",
    type: "活动视觉",
    category: "event",
    brand: "Backup",
    cover: "/media/EVENT/Backup/Backup-April Fools Day.mp4",
    poster: "/media/EVENT/Backup/Backup-April Fools Day-poster.jpg",
    images: ["/media/EVENT/Backup/Backup-April Fools Day.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 112,
    title: "Thailand Event Visual",
    type: "活动视觉",
    category: "event",
    brand: "Backup",
    cover: "/media/EVENT/Backup/Backup-Thailand Event Visual.mp4",
    poster: "/media/EVENT/Backup/Backup-Thailand Event Visual-poster.jpg",
    images: ["/media/EVENT/Backup/Backup-Thailand Event Visual.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 113,
    title: "Dragon Boat Festival",
    type: "活动视觉",
    category: "event",
    brand: "Backup",
    cover: "/media/EVENT/Backup/Backup-Dragon Boat Festival.mp4",
    poster: "/media/EVENT/Backup/Backup-Dragon Boat Festival-poster.jpg",
    images: ["/media/EVENT/Backup/Backup-Dragon Boat Festival.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 114,
    title: "New Year Eve Live Action Compositing",
    type: "活动视觉",
    category: "event",
    brand: "Backup",
    cover: "/media/EVENT/Backup/Backup-New Year Eve Live Action Compositing.mp4",
    poster: "/media/EVENT/Backup/Backup-New Year Eve Live Action Compositing-poster.jpg",
    images: ["/media/EVENT/Backup/Backup-New Year Eve Live Action Compositing.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 115,
    title: "Necklace",
    type: "活动视觉",
    category: "event",
    brand: "Backup",
    cover: "/media/EVENT/Backup/Backup-Necklace.mp4",
    poster: "/media/EVENT/Backup/Backup-Necklace-poster.jpg",
    images: ["/media/EVENT/Backup/Backup-Necklace.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 116,
    title: "Dragon Head Raising Festival",
    type: "活动视觉",
    category: "event",
    brand: "Backup",
    cover: "/media/EVENT/Backup/Backup-Dragon Head Raising Festival.mp4",
    poster: "/media/EVENT/Backup/Backup-Dragon Head Raising Festival-poster.jpg",
    images: ["/media/EVENT/Backup/Backup-Dragon Head Raising Festival.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 117,
    title: "Live Action Compositing",
    type: "活动视觉",
    category: "event",
    brand: "RHR",
    cover: "/media/EVENT/RHR/RHR-Live Action Compositing.mp4",
    poster: "/media/EVENT/RHR/RHR-Live Action Compositing-poster.jpg",
    images: ["/media/EVENT/RHR/RHR-Live Action Compositing.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 118,
    title: "Happy Chinese New Year",
    type: "活动视觉",
    category: "event",
    brand: "RHR",
    cover: "/media/EVENT/RHR/RHR-Happy Chinese New Year.mp4",
    poster: "/media/EVENT/RHR/RHR-Happy Chinese New Year-poster.jpg",
    images: ["/media/EVENT/RHR/RHR-Happy Chinese New Year.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 119,
    title: "Nuclear Fusion",
    type: "活动视觉",
    category: "event",
    brand: "TNT",
    cover: "/media/EVENT/TNT/TNT-Nuclear Fusion.mp4",
    poster: "/media/EVENT/TNT/TNT-Nuclear Fusion-poster.jpg",
    images: ["/media/EVENT/TNT/TNT-Nuclear Fusion.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 120,
    title: "Logo Animation",
    type: "活动视觉",
    category: "event",
    brand: "Hongdae Station",
    cover: "/media/EVENT/Hongdae Station/Hongdae Station-Logo Animation.mp4",
    poster: "/media/EVENT/Hongdae Station/Hongdae Station-Logo Animation-poster.jpg",
    images: ["/media/EVENT/Hongdae Station/Hongdae Station-Logo Animation.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 121,
    title: "End Card Money Gun JY",
    type: "活动视觉",
    category: "event",
    brand: "Hongdae Station",
    cover: "/media/EVENT/Hongdae Station/Hongdae Station-End Card Money Gun JY.mp4",
    poster: "/media/EVENT/Hongdae Station/Hongdae Station-End Card Money Gun JY-poster.jpg",
    images: ["/media/EVENT/Hongdae Station/Hongdae Station-End Card Money Gun JY.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 122,
    title: "Product Release",
    type: "活动视觉",
    category: "event",
    brand: "Future Creation",
    cover: "/media/EVENT/Future Creation/Future Creation-Product Release.mp4",
    poster: "/media/EVENT/Future Creation/Future Creation-Product Release-poster.jpg",
    images: ["/media/EVENT/Future Creation/Future Creation-Product Release.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 123,
    title: "Product Release 2",
    type: "活动视觉",
    category: "event",
    brand: "Future Creation",
    cover: "/media/EVENT/Future Creation/Future Creation-Product Release 2.mp4",
    poster: "/media/EVENT/Future Creation/Future Creation-Product Release 2-poster.jpg",
    images: ["/media/EVENT/Future Creation/Future Creation-Product Release 2.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 124,
    title: "Product Release 3",
    type: "活动视觉",
    category: "event",
    brand: "Future Creation",
    cover: "/media/EVENT/Future Creation/Future Creation-Product Release 3.mp4",
    poster: "/media/EVENT/Future Creation/Future Creation-Product Release 3-poster.jpg",
    images: ["/media/EVENT/Future Creation/Future Creation-Product Release 3.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 125,
    title: "Product Release 4",
    type: "活动视觉",
    category: "event",
    brand: "Future Creation",
    cover: "/media/EVENT/Future Creation/Future Creation-Product Release 4.mp4",
    poster: "/media/EVENT/Future Creation/Future Creation-Product Release 4-poster.jpg",
    images: ["/media/EVENT/Future Creation/Future Creation-Product Release 4.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 126,
    title: "Shipping Notice",
    type: "活动视觉",
    category: "event",
    brand: "Future Creation",
    cover: "/media/EVENT/Future Creation/Future Creation-Shipping Notice.mp4",
    poster: "/media/EVENT/Future Creation/Future Creation-Shipping Notice-poster.jpg",
    images: ["/media/EVENT/Future Creation/Future Creation-Shipping Notice.mp4"],
    mediaType: "video",
    featured: false
  },
  {
    id: 127,
    title: "Limited Time Event",
    type: "活动视觉",
    category: "event",
    brand: "Future Creation",
    cover: "/media/EVENT/Future Creation/Future Creation-Limited Time Event.mp4",
    poster: "/media/EVENT/Future Creation/Future Creation-Limited Time Event-poster.jpg",
    images: ["/media/EVENT/Future Creation/Future Creation-Limited Time Event.mp4"],
    mediaType: "video",
    featured: false
  }
];
